// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojwwmgqkdwpephzvgngn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qd3dtZ3FrZHdwZXBoenZnbmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjczNTYsImV4cCI6MjA2OTIwMzM1Nn0.IJD3_1cXtU5wBqQ-FJx2W4yL7Ps2sBQVdfdt3GkjMes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});